- name: configure dhcp agent
  template:
    src: dhcp_agent.ini.j2
    dest: /etc/neutron/dhcp_agent.ini
  notify:
    - restart neutron-dhcp-agent

- name: configure dnsmasq
  template:
    src: dnsmasq.conf.j2
    dest: /etc/neutron/dnsmasq.conf
  notify:
    - restart neutron-dhcp-agent

- meta: flush_handlers
