- name: configure service
  template:
    src: service.cfg.j2
    dest: /etc/haproxy/cfg.d/10-{{ haproxy_service_name }}.cfg
  notify:
    - assemble haproxy config
    - reload haproxy
  tags:
    - haproxy
    - haproxy-service
