- name: check if libvirt rbd secret set
  command: virsh secret-get-value {{ nova_libvirt_ceph_secret_uuid }}
  register: result
  changed_when: false
  failed_when: false

- name: generate libvirt rbd secret definition
  template:
    src: secret.xml.j2
    dest: /tmp/secret.xml
    owner: root
    group: root
    mode: 0600
  when: result.rc != 0

- name: define libvirt rbd secret
  command: virsh secret-define /tmp/secret.xml
  when: result.rc != 0

- name: set libvirt rbd secret
  command: virsh secret-set-value {{ nova_libvirt_ceph_secret_uuid }} {{ nova_libvirt_ceph_secret }}
  when: result.rc != 0
