- name: sync cinder db
  run_once: yes
  command: cinder-manage db sync
  when: openstack_auto_migrate

- name: restart cinder-api
  service:
    name: cinder-api
    state: restarted
  failed_when: false
  when: openstack_auto_restart

- name: restart cinder-scheduler
  service:
    name: cinder-scheduler
    state: restarted
  failed_when: false
  when: openstack_auto_restart

- name: restart cinder-volume
  service:
    name: cinder-volume
    state: restarted
  failed_when: false
  when: openstack_auto_restart
