nova_bind_address: "{{ openstack_internal_address }}"

# Scheduler configuration
nova_scheduler_default_filters:
  - AggregateInstanceExtraSpecsFilter
  - RetryFilter
  - AvailabilityZoneFilter
  - RamFilter
  - ComputeFilter
  - ImagePropertiesFilter
  - ServerGroupAntiAffinityFilter
  - ServerGroupAffinityFilter
  - SameHostFilter
  - DifferentHostFilter

nova_cpu_allocation_ratio: 16.0
nova_disk_allocation_ratio: 1.0
nova_ram_allocation_ratio: 1.5
nova_ram_weight_multiplier: 1.0
