- name: create initial keyring
  run_once: yes
  command: >
    ceph-authtool /var/lib/ceph/tmp/ceph.mon.keyring
      --create-keyring
      --gen-key
      --name mon.
      --cap mon "allow *"
  args:
    creates: /var/lib/ceph/tmp/ceph.mon.keyring

- name: fetch initial keyring
  run_once: yes
  fetch:
    src: /var/lib/ceph/tmp/ceph.mon.keyring
    dest: fetch/ceph.mon.keyring
    flat: yes

- name: copy initial keyring
  copy:
    src: fetch/ceph.mon.keyring
    dest: /var/lib/ceph/tmp/ceph.mon.keyring
    owner: ceph
    group: ceph
    mode: 0640

- name: deploy monitor
  command: >
    ceph-mon --mkfs
      -i {{ ansible_hostname }}
      --fsid {{ ceph_fsid }}
      --setuser ceph
      --setgroup ceph
      --keyring /var/lib/ceph/tmp/ceph.mon.keyring
  args:
    creates: /var/lib/ceph/mon/ceph-{{ ansible_hostname }}/keyring

- name: activate monitor
  file:
    path: /var/lib/ceph/mon/ceph-{{ ansible_hostname }}/{{ item }}
    owner: ceph
    group: ceph
    state: touch
  with_items:
    - done
    - upstart
  changed_when: false

- name: ensure monitor started
  service:
    name: ceph-mon
    args: id={{ ansible_hostname }}
    state: started
