- name: generate bootstrap keys
  command: ceph-create-keys -i {{ ansible_hostname }}
  changed_when: false

- name: fetch osd bootstrap keyring
  run_once: yes
  fetch:
    src: /var/lib/ceph/bootstrap-osd/ceph.keyring
    dest: fetch/ceph.client.bootstrap-osd.keyring
    flat: yes
