- name: configure rabbitmq
  template:
    src: rabbitmq.config.j2
    dest: /etc/rabbitmq/rabbitmq.config
  notify:
    - restart rabbitmq

- name: configure erlang cookie
  template:
    src: cookie.j2
    dest: /var/lib/rabbitmq/.erlang.cookie
    owner: rabbitmq
    group: rabbitmq
    mode: 0400
  when: rabbitmq_clustered
  register: result
  notify:
    - restart rabbitmq

- include: reset.yml
  when: result|changed

- meta: flush_handlers

- name: wait for rabbitmq to start
  wait_for:
    port: 5672

- name: ensure ha mode on all queues
  run_once: yes
  rabbitmq_policy:
    name: ha
    pattern: .*
    tags:
      ha-mode: all
  when: rabbitmq_clustered

- name: remove guest user
  rabbitmq_user:
    user: guest
    state: absent

- name: add admin user
  rabbitmq_user:
    user: admin
    password: "{{ rabbitmq_admin_password }}"
    tags: administrator
    state: present
