- name: add apt key
  apt_key:
    id: 6026DFCA
    url: https://www.rabbitmq.com/rabbitmq-release-signing-key.asc

- name: add apt repository
  apt_repository:
    repo: deb http://www.rabbitmq.com/debian testing main
    update_cache: yes

- name: install rabbitmq
  apt:
    pkg: rabbitmq-server
    state: present

- name: enable management plugin
  rabbitmq_plugin:
    name: rabbitmq_management
    new_only: yes
    state: enabled
