openstack_group_haproxy: haproxy
openstack_group_mysql: mysql
openstack_group_rabbitmq: rabbitmq
openstack_group_memcached: memcached
openstack_group_keystone: keystone
openstack_group_nova_controller: nova-controller
openstack_group_nova_compute: nova-compute

openstack_region: RegionOne

openstack_lb_vip: localhost

openstack_internal_address: "{{ ansible_default_ipv4.address }}"
openstack_internal_interface: eth0

keystone_auth_uri: http://{{ openstack_lb_vip }}:5000
keystone_auth_url: http://{{ openstack_lb_vip }}:35357
