ceph_group_mon: ceph-mon

ceph_fsid: ffffffff-ffff-ffff-ffff-ffffffffffff
ceph_public_network: null
ceph_cluster_network: null

ceph_osd_journal_size: 1024
ceph_osd_pool_default_size: 2
ceph_osd_pool_default_min_size: 1
ceph_osd_pool_default_pg_num: 128
ceph_osd_pool_default_pgp_num: 128
