- name: configure openvswitch agent
  template:
    src: openvswitch_agent.ini.j2
    dest: /etc/neutron/plugins/ml2/openvswitch_agent.ini
  notify:
    - restart neutron-plugin-openvswitch-agent

- meta: flush_handlers
