- name: install chrony
  apt:
    pkg: chrony
    state: present
  tags:
    - chrony
    - chrony-install

- name: configure chrony
  template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
  notify:
    - restart chrony
  tags:
    - chrony
    - chrony-configure

- meta: flush_handlers
