- hosts: haproxy
  roles:
    - role: haproxy-service
      haproxy_service_name: cinder-api
      haproxy_service_port: 8776
      haproxy_service_group: cinder-controller

- hosts: keystone
  roles:
    - name: keystone-service
      keystone_service_name: cinder
      keystone_service_type: volume
      keystone_endpoint_public: "{{ cinder_keystone_endpoint_volume_public }}"
      keystone_endpoint_internal: "{{ cinder_keystone_endpoint_volume_internal }}"
      keystone_endpoint_admin: "{{ cinder_keystone_endpoint_volume_admin }}"

    - name: keystone-service
      keystone_service_name: cinderv2
      keystone_service_type: volumev2
      keystone_endpoint_public: "{{ cinder_keystone_endpoint_volumev2_public }}"
      keystone_endpoint_internal: "{{ cinder_keystone_endpoint_volumev2_internal }}"
      keystone_endpoint_admin: "{{ cinder_keystone_endpoint_volumev2_admin }}"

    - name: keystone-user
      keystone_user: "{{ cinder_keystone_user }}"
      keystone_password: "{{ cinder_keystone_password }}"
      keystone_project: "{{ cinder_keystone_project }}"

- hosts: mysql
  roles:
    - name: mysql-service
      mysql_service_db: "{{ cinder_mysql_db }}"
      mysql_service_user: "{{ cinder_mysql_user }}"
      mysql_service_password: "{{ cinder_mysql_password }}"

- hosts: rabbitmq
  roles:
    - name: rabbitmq-service
      rabbitmq_vhost: "{{ cinder_rabbitmq_vhost }}"
      rabbitmq_user: "{{ cinder_rabbitmq_user }}"
      rabbitmq_password: "{{ cinder_rabbitmq_password }}"

- hosts: ceph-mon
  tasks:
    - name: ensure volumes pool
      run_once: yes
      ceph_pool:
        name: volumes
        state: present

    - name: create cinder ceph keyring
      run_once: yes
      command: >
        ceph auth get-or-create client.cinder
          mon 'allow r'
          osd 'allow class-read object_prefix rbd_children, allow rwx pool=volumes, allow rx pool=images'
        -o /etc/ceph/ceph.client.cinder.keyring
      args:
        creates: /etc/ceph/ceph.client.cinder.keyring

    - name: fetch cinder ceph keyring
      run_once: yes
      fetch:
        src: /etc/ceph/ceph.client.cinder.keyring
        dest: fetch/ceph.client.cinder.keyring
        flat: yes

- hosts: cinder-controller
  roles:
    - cinder-controller

- hosts: cinder-volume
  roles:
    - ceph-common
    - cinder-volume
  post_tasks:
    - name: copy cinder ceph keyring
      copy:
        src: fetch/ceph.client.cinder.keyring
        dest: /etc/ceph/ceph.client.cinder.keyring
        owner: cinder
        group: cinder
        mode: 0640
