- hosts: haproxy
  roles:
    - role: haproxy-service
      haproxy_service_name: neutron-server
      haproxy_service_port: 8774
      haproxy_service_group: neutron-controller

- hosts: keystone
  roles:
    - name: keystone-service
      keystone_service_name: neutron
      keystone_service_type: network
      keystone_endpoint_public: "{{ neutron_keystone_endpoint_network_public }}"
      keystone_endpoint_internal: "{{ neutron_keystone_endpoint_network_internal }}"
      keystone_endpoint_admin: "{{ neutron_keystone_endpoint_network_admin }}"

    - name: keystone-user
      keystone_user: "{{ neutron_keystone_user }}"
      keystone_password: "{{ neutron_keystone_password }}"
      keystone_project: "{{ neutron_keystone_project }}"

- hosts: mysql
  roles:
    - name: mysql-service
      mysql_service_db: "{{ neutron_mysql_db }}"
      mysql_service_user: "{{ neutron_mysql_user }}"
      mysql_service_password: "{{ neutron_mysql_password }}"

- hosts: rabbitmq
  roles:
    - name: rabbitmq-service
      rabbitmq_vhost: "{{ neutron_rabbitmq_vhost }}"
      rabbitmq_user: "{{ neutron_rabbitmq_user }}"
      rabbitmq_password: "{{ neutron_rabbitmq_password }}"

- hosts: neutron-controller
  roles:
    - neutron-server

- hosts: neutron-network
  roles:
    - neutron-openvswitch-agent
    - neutron-l3-agent
    - neutron-dhcp-agent

- hosts: nova-compute
  roles:
    - neutron-openvswitch-agent
    - name: neutron-l3-agent
      neutron_l3_agent_mode: dvr
      when: neutron_l3_distributed
