- name: install heat-api
  apt:
    pkg: heat-api
    state: present

- name: install heat-api-cfn-cfn
  apt:
    pkg: heat-api-cfn
    state: present

- name: install heat-engine
  apt:
    pkg: heat-engine
    state: present
